### PR TITLE
Uirevamp

### PR DESCRIPTION
**Pull request by Parth59**
Following are the issues that are resolved with the Following PR.
i) Implement Desktop friendly UI :- https://github.com/shahrk/polly/issues/12
ii) Revamp Admin dashboard :- https://github.com/shahrk/polly/issues/9
iii) Revamp Player Question :- https://github.com/shahrk/polly/issues/11

Kindly review the same.

### CODE REVIEW

**Comment by Nirav1929** [comment]
Is this handling desktop website?

**Comment by Parth59** [comment]
Yes. I have used bootstrap to make it cross browser compatible.

**Comment by Nirav1929** [comment]
Aren't we using the same documentation style checker here?

**Comment by Parth59** [comment]
Yes. I am following all the guidelines and processes.

**Comment by Nirav1929** [comment]
I hope it is not breaking already working mobile version of this

**Comment by Parth59** [comment]
Yes. I used chrome browser's checker to check the responsiveness of the UI.

**Comment by Nirav1929** [comment]
Okay looks good.
I am approving this

**Pull request merged**
