### PR TITLE
Feature backend

### PR DESCRIPTION
**Pull request by BhargavJethwa**
Following are the open backend issues that are resolved with this PR
1) #20 
2) #13 
3) #14 

Kindly review it. @shahrk @Nirav1929

### CODE REVIEW

**Comment by Parth59** [comment]
I am seeing conflicts over here. @BhargavJethwa or @Nirav1929  can you resolve those ?

**Comment by Nirav1929** [comment]
Reviewing

**Comment by Parth59** [comment]
I have hovered around and reviewed the new code and it looks good to me to be pushed in the main branch.  Requesting you to kindly resolve the merge conflicts. I think those conflicts are caused because of my recent push and Bhargav code causing conflict.

**Comment by Nirav1929** [comment]
Looks good.

**Comment by Nirav1929** [comment]
Solved merge conflicts.
Should be good to go

**Comment by Parth59** [comment]
Done

**Pull request merged**
