### PR TITLE
Raj/UI ux revamp

### PR DESCRIPTION
**Pull request by shahrk**

### CODE REVIEW

**Comment by shahrk** [comment]
Added changes for the UI revamp. Let me know how this looks

**Comment by Nirav1929** [comment]
Reviewing

**Comment by Nirav1929** [comment]
Have you tried running it? 
Last time frontend on desktop was crashing

**Comment by shahrk** [comment]
Yup, all the tests are passing as well.

**Comment by Nirav1929** [comment]
Great. 
Also is this integrated supporting correct answer we have added in backend?

**Comment by shahrk** [comment]
Yup, I integrated it with the latest backend.

**Pull request merged**
